# Generated by Django 4.2 on 2023-04-26 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='factory_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='model_year',
            field=models.IntegerField(),
        ),
    ]
